source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'activeadmin', github: 'gregbell/active_admin'
gem 'bcrypt-ruby'
gem 'coffee-rails', '~> 4.0.0'
gem 'exception_notification'
gem 'geocoder'
gem 'houston'
gem 'kaminari'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'newrelic_rpm'
gem 'pg'
gem 'protected_attributes'
gem 'redis'
gem 'sass-rails', '~> 4.0.1'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'websocket-rails'