development:
  adapter: postgresql
  encoding: utf8
  database: lights_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: lights_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: lights_production
  pool: 5
  username: 
  password: